#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-datanucleus-rdbms
Version  : 3.2.9
Release  : 1
URL      : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.jar
Source0  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.jar
Source1  : https://repo1.maven.org/maven2/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-datanucleus-rdbms-data = %{version}-%{release}

%description
RDBMS Plugin
============
This project provides support for persistence to RDBMS datastores.

%package data
Summary: data components for the mvn-datanucleus-rdbms package.
Group: Data

%description data
data components for the mvn-datanucleus-rdbms package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.jar
/usr/share/java/.m2/repository/org/datanucleus/datanucleus-rdbms/3.2.9/datanucleus-rdbms-3.2.9.pom
